#!/usr/bin/env python3
"""
JSC Intra-Block Split Opportunity Analyzer

This script analyzes the log file generated by JSC's register allocator to identify
intra-block split opportunities and determine which ones were optimized away by the
fixObviousSpills pass.

Usage:
    python3 analyze-split-opportunities.py /path/to/split-analysis.log
"""

import re
import sys
from dataclasses import dataclass, field
from typing import List, Dict, Set, Optional, Tuple
from collections import defaultdict


@dataclass
class UseCluster:
    """Represents a single use cluster within a basic block."""
    bb_num: int
    inst_start: int
    inst_end: int
    num_uses: int
    density: float
    frequency: float


@dataclass
class SplitOpportunity:
    """Represents an intra-block split opportunity."""
    tmp_name: str
    num_clusters: int
    total_benefit: float
    clusters: List[UseCluster] = field(default_factory=list)
    spill_slot: Optional[str] = None
    basic_blocks: Set[int] = field(default_factory=set)


@dataclass
class SpillSlotLoad:
    """Represents a load from a spill slot in the IR."""
    bb_num: int
    inst_line: str
    spill_slot: str
    dest_reg: str
    line_num: int


@dataclass
class AnalysisResult:
    """Results of analyzing a single compilation unit."""
    opportunities: List[SplitOpportunity]
    spill_mappings: Dict[str, str]  # tmp -> spill slot
    loads_before: List[SpillSlotLoad]
    loads_after: List[SpillSlotLoad]
    fixed_loads: Dict[Tuple[int, str], bool]  # (bb_num, spill_slot) -> was_fixed


def parse_opportunity_header(line: str) -> Optional[Tuple[str, int, float]]:
    """
    Parse the opportunity header line.
    Example: "Spilled: %tmp586 with 2 use clusters (total benefit: 137.833344)"
    Returns: (tmp_name, num_clusters, benefit)
    """
    match = re.match(
        r'Spilled:\s+(%tmp\d+)\s+with\s+(\d+)\s+use\s+clusters?\s+\(total\s+benefit:\s+([\d.]+)\)',
        line
    )
    if match:
        return match.group(1), int(match.group(2)), float(match.group(3))
    return None


def parse_cluster_line(line: str) -> Optional[UseCluster]:
    """
    Parse a cluster line.
    Example: "  BB#2 [inst 4-5] 3 uses, density=1.500000, freq=1.000000"
    Returns: UseCluster object
    """
    match = re.match(
        r'\s+BB#(\d+)\s+\[inst\s+(\d+)-(\d+)\]\s+(\d+)\s+uses?,\s+density=([\d.]+),\s+freq=([\d.]+)',
        line
    )
    if match:
        return UseCluster(
            bb_num=int(match.group(1)),
            inst_start=int(match.group(2)),
            inst_end=int(match.group(3)),
            num_uses=int(match.group(4)),
            density=float(match.group(5)),
            frequency=float(match.group(6))
        )
    return None


def parse_spill_mapping(line: str) -> Optional[Tuple[str, str]]:
    """
    Parse a spill slot mapping line.
    Example: "  %tmp586 -> spill5 (8 bytes)"
    Returns: (tmp_name, spill_slot)
    """
    match = re.match(r'\s+(%tmp\d+)\s+->\s+(spill\d+)\s+\(', line)
    if match:
        return match.group(1), match.group(2)
    return None


def parse_air_instruction(line: str) -> Optional[Tuple[int, str, str]]:
    """
    Parse an AIR instruction line to extract BB number and check for spill slot loads.
    Example: "Air BB#10: ; frequency = 1.000000"
    Example: "Air     Move (spill42), %rax"
    Example: "Air     Move32 (spill42), %x0"
    Returns: (bb_num, instruction, spill_slot) or None
    """
    # Check for BB header
    bb_match = re.match(r'Air BB#(\d+):', line)
    if bb_match:
        return int(bb_match.group(1)), '', ''

    # Check for Move instruction with spill slot as source
    # Matches: Move (spillX), Move32 (spillX), Move64 (spillX), Move<...> (spillX)
    inst_match = re.match(r'Air\s+Move(?:\d+|<[^>]+>)?\s+\((spill\d+)\)', line)
    if inst_match:
        return -1, line.strip(), inst_match.group(1)

    return None


def parse_log_section(lines: List[str], start_idx: int) -> AnalysisResult:
    """
    Parse a single compilation unit section (from opportunities through both IR dumps).
    """
    opportunities = []
    spill_mappings = {}
    loads_before = []
    loads_after = []
    fixed_loads = {}

    idx = start_idx
    state = 'opportunities'
    current_opp = None
    current_bb = -1

    while idx < len(lines):
        line = lines[idx]

        # Check for section boundaries
        if '=== SPILL SLOT MAPPING FOR OPPORTUNITIES ===' in line:
            state = 'mappings'
            idx += 1
            continue
        elif '=== AIR BEFORE REGISTER ASSIGNMENT' in line:
            state = 'ir_before'
            current_bb = -1
            idx += 1
            continue
        elif '=== END IR ===' in line or '=== AIR AFTER fixObviousSpills ===' in line:
            if state == 'ir_before':
                state = 'ir_after'
                current_bb = -1
            elif state == 'ir_after':
                # End of this section
                break
            idx += 1
            continue
        elif '=== END IR (after fixObviousSpills) ===' in line:
            # End of this section
            break
        elif line.strip() == '' or line.startswith('   num'):
            # Skip empty lines and statistics lines
            idx += 1
            continue

        # Parse based on current state
        if state == 'opportunities':
            if '=== INTRA-BLOCK SPLIT OPPORTUNITY ===' in line:
                if current_opp:
                    opportunities.append(current_opp)
                current_opp = None
                idx += 1
                continue

            if not current_opp:
                # Try to parse opportunity header
                header = parse_opportunity_header(line)
                if header:
                    tmp_name, num_clusters, benefit = header
                    current_opp = SplitOpportunity(
                        tmp_name=tmp_name,
                        num_clusters=num_clusters,
                        total_benefit=benefit
                    )
            else:
                # Try to parse cluster line
                cluster = parse_cluster_line(line)
                if cluster:
                    current_opp.clusters.append(cluster)
                    current_opp.basic_blocks.add(cluster.bb_num)

        elif state == 'mappings':
            mapping = parse_spill_mapping(line)
            if mapping:
                tmp_name, spill_slot = mapping
                spill_mappings[tmp_name] = spill_slot

        elif state in ['ir_before', 'ir_after']:
            parsed = parse_air_instruction(line)
            if parsed:
                bb_num, instruction, spill_slot = parsed
                if bb_num >= 0:
                    current_bb = bb_num
                elif spill_slot and current_bb >= 0:
                    # Found a spill slot load
                    load = SpillSlotLoad(
                        bb_num=current_bb,
                        inst_line=instruction,
                        spill_slot=spill_slot,
                        dest_reg='',
                        line_num=idx
                    )
                    if state == 'ir_before':
                        loads_before.append(load)
                    else:
                        loads_after.append(load)

        idx += 1

    # Add the last opportunity if any
    if current_opp:
        opportunities.append(current_opp)

    # Match spill slots to opportunities
    for opp in opportunities:
        if opp.tmp_name in spill_mappings:
            opp.spill_slot = spill_mappings[opp.tmp_name]

    # Analyze which loads were fixed
    # Build a set of (bb, spill_slot) pairs from before
    loads_before_set = {(load.bb_num, load.spill_slot) for load in loads_before}
    loads_after_set = {(load.bb_num, load.spill_slot) for load in loads_after}

    # A load is "fixed" if it appears in before but not in after
    for key in loads_before_set:
        fixed_loads[key] = key not in loads_after_set

    return AnalysisResult(
        opportunities=opportunities,
        spill_mappings=spill_mappings,
        loads_before=loads_before,
        loads_after=loads_after,
        fixed_loads=fixed_loads
    )


def parse_log_file(filepath: str) -> List[AnalysisResult]:
    """
    Parse the entire log file, which may contain multiple compilation units.
    """
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"ERROR: Log file not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Failed to read log file: {e}", file=sys.stderr)
        sys.exit(1)

    results = []
    idx = 0

    print(f"Parsing log file ({len(lines)} lines)...")

    # Find all compilation unit starts
    while idx < len(lines):
        if '=== INTRA-BLOCK SPLIT OPPORTUNITY ===' in lines[idx]:
            # Found the start of a new section
            result = parse_log_section(lines, idx)
            if result.opportunities:
                results.append(result)
            # Skip forward to avoid re-parsing
            idx += 1000  # Heuristic: skip ahead to speed up parsing
        else:
            idx += 1

    return results


def analyze_results(results: List[AnalysisResult]) -> Dict:
    """
    Aggregate and analyze results from all compilation units.
    """
    # Collect all opportunities
    all_opportunities = []
    for result in results:
        all_opportunities.extend(result.opportunities)

    # Sort by benefit descending
    all_opportunities.sort(key=lambda x: x.total_benefit, reverse=True)

    # Analyze top 10
    top_10_analysis = []
    for opp in all_opportunities[:10]:
        # Find which result this opportunity belongs to
        parent_result = None
        for result in results:
            if opp in result.opportunities:
                parent_result = result
                break

        if not parent_result:
            continue

        # Count how many blocks had loads that were fixed
        blocks_fixed = 0
        if opp.spill_slot:
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in parent_result.fixed_loads and parent_result.fixed_loads[key]:
                    blocks_fixed += 1

        top_10_analysis.append({
            'opportunity': opp,
            'blocks_fixed': blocks_fixed,
            'total_blocks': len(opp.basic_blocks),
            'fix_rate': blocks_fixed / len(opp.basic_blocks) if opp.basic_blocks else 0
        })

    # Overall statistics
    total_opportunities = len(all_opportunities)
    opportunities_with_some_fixes = 0
    opportunities_fully_fixed = 0

    for result in results:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            if blocks_fixed > 0:
                opportunities_with_some_fixes += 1
            if blocks_fixed == len(opp.basic_blocks):
                opportunities_fully_fixed += 1

    return {
        'all_opportunities': all_opportunities,
        'top_10_analysis': top_10_analysis,
        'total_opportunities': total_opportunities,
        'opportunities_with_some_fixes': opportunities_with_some_fixes,
        'opportunities_fully_fixed': opportunities_fully_fixed,
        'results': results
    }


def generate_report(analysis: Dict) -> str:
    """
    Generate a human-readable report from the analysis.
    """
    report_lines = []

    report_lines.append("=" * 80)
    report_lines.append("JSC INTRA-BLOCK SPLIT OPPORTUNITY ANALYSIS REPORT")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append("This report analyzes intra-block split opportunities identified by JSC's")
    report_lines.append("register allocator and determines which ones were optimized away by the")
    report_lines.append("fixObviousSpills pass.")
    report_lines.append("")
    report_lines.append("KEY INSIGHT:")
    report_lines.append("- If fixObviousSpills optimized all blocks for an opportunity, splitting")
    report_lines.append("  is NOT needed (the redundant spills were already removed).")
    report_lines.append("- If blocks remain unfixed, intra-block splitting could provide benefit")
    report_lines.append("  by keeping the value in a register within those hot blocks.")
    report_lines.append("")

    # Overall statistics
    report_lines.append("OVERALL STATISTICS")
    report_lines.append("-" * 80)
    report_lines.append(f"Total split opportunities found: {analysis['total_opportunities']}")
    report_lines.append(f"Opportunities with some blocks fixed: {analysis['opportunities_with_some_fixes']} "
                       f"({100.0 * analysis['opportunities_with_some_fixes'] / max(1, analysis['total_opportunities']):.1f}%)")
    report_lines.append(f"Opportunities fully fixed: {analysis['opportunities_fully_fixed']} "
                       f"({100.0 * analysis['opportunities_fully_fixed'] / max(1, analysis['total_opportunities']):.1f}%)")
    not_fixed = analysis['total_opportunities'] - analysis['opportunities_with_some_fixes']
    report_lines.append(f"Opportunities NOT fixed at all: {not_fixed} "
                       f"({100.0 * not_fixed / max(1, analysis['total_opportunities']):.1f}%)")
    report_lines.append("")

    # Top 10 opportunities
    report_lines.append("TOP 10 SPLIT OPPORTUNITIES (by benefit)")
    report_lines.append("-" * 80)
    report_lines.append(f"{'Rank':<6}{'Tmp':<12}{'Benefit':<12}{'Clusters':<10}{'Blocks':<8}{'Fixed':<8}{'Fix %':<8}{'Spill Slot':<12}")
    report_lines.append("-" * 80)

    for rank, item in enumerate(analysis['top_10_analysis'], 1):
        opp = item['opportunity']
        report_lines.append(
            f"{rank:<6}"
            f"{opp.tmp_name:<12}"
            f"{opp.total_benefit:<12.2f}"
            f"{opp.num_clusters:<10}"
            f"{item['total_blocks']:<8}"
            f"{item['blocks_fixed']:<8}"
            f"{item['fix_rate']*100:<7.1f}%"
            f"{opp.spill_slot or 'N/A':<12}"
        )

    report_lines.append("")

    # Detailed analysis of top 10
    report_lines.append("DETAILED ANALYSIS OF TOP 10 OPPORTUNITIES")
    report_lines.append("-" * 80)

    for rank, item in enumerate(analysis['top_10_analysis'], 1):
        opp = item['opportunity']
        report_lines.append("")
        report_lines.append(f"#{rank}: {opp.tmp_name} (benefit: {opp.total_benefit:.2f})")
        report_lines.append(f"  Spill slot: {opp.spill_slot or 'N/A'}")
        report_lines.append(f"  Number of clusters: {opp.num_clusters}")
        report_lines.append(f"  Basic blocks involved: {sorted(opp.basic_blocks)[:10]}"
                           f"{' ...' if len(opp.basic_blocks) > 10 else ''}")
        report_lines.append(f"  Blocks with loads fixed: {item['blocks_fixed']}/{item['total_blocks']} "
                           f"({item['fix_rate']*100:.1f}%)")

        if item['fix_rate'] < 1.0:
            report_lines.append(f"  ** NEEDS SPLITTING: Not all blocks were optimized by fixObviousSpills **")

    report_lines.append("")

    # Opportunities that need splitting (not fully fixed)
    needs_splitting = []
    for result in analysis['results']:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            if blocks_fixed < len(opp.basic_blocks):
                needs_splitting.append((opp, blocks_fixed, len(opp.basic_blocks)))

    # Sort by benefit
    needs_splitting.sort(key=lambda x: x[0].total_benefit, reverse=True)

    report_lines.append("OPPORTUNITIES THAT NEED SPLITTING (not fully optimized)")
    report_lines.append("-" * 80)
    report_lines.append(f"Total: {len(needs_splitting)} opportunities")
    report_lines.append("")
    report_lines.append(f"{'Tmp':<12}{'Benefit':<12}{'Clusters':<10}{'Fixed':<15}{'Spill Slot':<12}")
    report_lines.append("-" * 80)

    for opp, fixed, total in needs_splitting[:50]:  # Show top 50
        report_lines.append(
            f"{opp.tmp_name:<12}"
            f"{opp.total_benefit:<12.2f}"
            f"{opp.num_clusters:<10}"
            f"{fixed}/{total:<13}"
            f"{opp.spill_slot or 'N/A':<12}"
        )

    if len(needs_splitting) > 50:
        report_lines.append(f"... and {len(needs_splitting) - 50} more")

    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append("END OF REPORT")
    report_lines.append("=" * 80)

    return "\n".join(report_lines)


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 analyze-split-opportunities.py <log-file>", file=sys.stderr)
        print("", file=sys.stderr)
        print("Example:", file=sys.stderr)
        print("  python3 analyze-split-opportunities.py /tmp/split-analysis.log", file=sys.stderr)
        sys.exit(1)

    log_file = sys.argv[1]

    print(f"Analyzing JSC split opportunity log: {log_file}")
    print("")

    # Parse the log file
    results = parse_log_file(log_file)

    if not results:
        print("WARNING: No split opportunities found in the log file.", file=sys.stderr)
        print("The log file may be incomplete or in an unexpected format.", file=sys.stderr)
        sys.exit(0)

    print(f"Found {len(results)} compilation units with split opportunities.")
    print("")

    # Analyze the results
    analysis = analyze_results(results)

    # Generate and print the report
    report = generate_report(analysis)
    print(report)

    # Optionally save to file
    output_file = log_file.rsplit('.', 1)[0] + '_analysis_report.txt'
    try:
        with open(output_file, 'w') as f:
            f.write(report)
        print("")
        print(f"Report saved to: {output_file}")
    except Exception as e:
        print(f"Warning: Could not save report to file: {e}", file=sys.stderr)


if __name__ == '__main__':
    main()
