#!/usr/bin/env python3
"""
JSC Intra-Block Split Opportunity Analyzer

This script analyzes the log file generated by JSC's register allocator to identify
intra-block split opportunities and determine which ones were optimized away by the
fixObviousSpills pass.

The analysis helps prioritize which opportunities would benefit most from implementing
intra-block splitting in the register allocator.

Key Concepts:
-------------
- Split Opportunity: A temporary variable that was spilled but has multiple "use clusters"
  within individual basic blocks, suggesting it could benefit from being kept in a register
  within those blocks.

- fixObviousSpills: An optimization pass that removes redundant spill loads/stores by
  reusing values already in registers.

- If fixObviousSpills already optimized all blocks for an opportunity, implementing
  splitting would provide no additional benefit (the work is already done).

- Opportunities where blocks remain unfixed are prime candidates for splitting, especially
  those with high benefit scores and high frequency.

Output Files:
-------------
- *_analysis_report.txt: Human-readable analysis report
- *_analysis.csv: CSV file with all opportunities for further analysis in Excel/spreadsheet

Usage:
------
    python3 analyze-split-opportunities.py /path/to/split-analysis.log

Example:
--------
    python3 analyze-split-opportunities.py /tmp/split-analysis.log
"""

import re
import sys
import csv
from dataclasses import dataclass, field
from typing import List, Dict, Set, Optional, Tuple
from collections import defaultdict


@dataclass
class UseCluster:
    """Represents a single use cluster within a basic block."""
    bb_num: int
    inst_start: int
    inst_end: int
    num_uses: int
    density: float
    frequency: float


@dataclass
class SplitOpportunity:
    """Represents an intra-block split opportunity."""
    tmp_name: str
    num_clusters: int
    total_benefit: float
    clusters: List[UseCluster] = field(default_factory=list)
    spill_slot: Optional[str] = None
    basic_blocks: Set[int] = field(default_factory=set)
    test_name: Optional[str] = None  # JS3 test name (if available)
    function_name: Optional[str] = None  # Function name (if available)


@dataclass
class SpillSlotLoad:
    """Represents a load from a spill slot in the IR."""
    bb_num: int
    inst_line: str
    spill_slot: str
    dest_reg: str
    line_num: int


@dataclass
class IRBasicBlock:
    """Represents a basic block in the IR."""
    bb_num: int
    frequency: float
    instructions: List[str] = field(default_factory=list)
    line_start: int = 0
    line_end: int = 0


@dataclass
class IRSection:
    """Complete IR section (before or after fixObviousSpills)."""
    blocks: Dict[int, IRBasicBlock] = field(default_factory=dict)  # bb_num -> block
    is_after_fix: bool = False


@dataclass
class AnalysisResult:
    """Results of analyzing a single compilation unit."""
    opportunities: List[SplitOpportunity]
    spill_mappings: Dict[str, str]  # tmp -> spill slot
    loads_before: List[SpillSlotLoad]
    loads_after: List[SpillSlotLoad]
    fixed_loads: Dict[Tuple[int, str], bool]  # (bb_num, spill_slot) -> was_fixed
    ir_before: Optional[IRSection] = None
    ir_after: Optional[IRSection] = None
    test_name: Optional[str] = None  # JS3 test name (if available)
    compilation_unit: Optional[str] = None  # Compilation unit identifier (if available)


def parse_opportunity_header(line: str) -> Optional[Tuple[str, int, float]]:
    """
    Parse the opportunity header line.
    Example: "Spilled: %tmp586 with 2 use clusters (total benefit: 137.833344)"
    Returns: (tmp_name, num_clusters, benefit)
    """
    match = re.match(
        r'Spilled:\s+(%tmp\d+)\s+with\s+(\d+)\s+use\s+clusters?\s+\(total\s+benefit:\s+([\d.]+)\)',
        line
    )
    if match:
        return match.group(1), int(match.group(2)), float(match.group(3))
    return None


def parse_cluster_line(line: str) -> Optional[UseCluster]:
    """
    Parse a cluster line.
    Example: "  BB#2 [inst 4-5] 3 uses, density=1.500000, freq=1.000000"
    Returns: UseCluster object
    """
    match = re.match(
        r'\s+BB#(\d+)\s+\[inst\s+(\d+)-(\d+)\]\s+(\d+)\s+uses?,\s+density=([\d.]+),\s+freq=([\d.]+)',
        line
    )
    if match:
        return UseCluster(
            bb_num=int(match.group(1)),
            inst_start=int(match.group(2)),
            inst_end=int(match.group(3)),
            num_uses=int(match.group(4)),
            density=float(match.group(5)),
            frequency=float(match.group(6))
        )
    return None


def parse_spill_mapping(line: str) -> Optional[Tuple[str, str]]:
    """
    Parse a spill slot mapping line.
    Example: "  %tmp586 -> spill5 (8 bytes)"
    Returns: (tmp_name, spill_slot)
    """
    match = re.match(r'\s+(%tmp\d+)\s+->\s+(spill\d+)\s+\(', line)
    if match:
        return match.group(1), match.group(2)
    return None


def parse_air_instruction(line: str) -> Optional[Tuple[int, str, str, float]]:
    """
    Parse an AIR instruction line to extract BB number and check for spill slot loads.
    Example: "Air BB#10: ; frequency = 1.000000"
    Example: "Air     Move (spill42), %rax"
    Example: "Air     Move32 (spill42), %x0"
    Returns: (bb_num, instruction, spill_slot, frequency) or None
    """
    # Check for BB header with frequency
    bb_match = re.match(r'Air BB#(\d+):\s*;\s*frequency\s*=\s*([\d.]+)', line)
    if bb_match:
        return int(bb_match.group(1)), '', '', float(bb_match.group(2))

    # Check for BB header without frequency
    bb_match = re.match(r'Air BB#(\d+):', line)
    if bb_match:
        return int(bb_match.group(1)), '', '', 1.0

    # Check for Move instruction with spill slot as source
    # Matches: Move (spillX), Move32 (spillX), Move64 (spillX), Move<...> (spillX)
    inst_match = re.match(r'Air\s+Move(?:\d+|<[^>]+>)?\s+\((spill\d+)\)', line)
    if inst_match:
        return -1, line.strip(), inst_match.group(1), 0.0

    return None


def parse_test_name(lines: List[str], start_idx: int, look_back: int = 100000) -> Optional[str]:
    """
    Try to find a test name by looking backwards from the current position.
    Searches for patterns like:
    - "Running <test-name>:"
    - "Running: <test-name>"
    - "Test: <test-name>"
    - "<test-name>.js"
    Returns test name if found, None otherwise.
    """
    # Look backwards from start_idx
    for i in range(start_idx - 1, max(0, start_idx - look_back), -1):
        line = lines[i]

        # Pattern: Running test-name: (JetStream3 format)
        match = re.match(r'^Running\s+([^:]+):', line)
        if match:
            return match.group(1).strip()

        # Pattern: Running: testname or Test: testname
        match = re.search(r'(?:Running|Test):\s*(\S+)', line)
        if match:
            return match.group(1)

        # Pattern: testname.js
        match = re.search(r'([a-zA-Z0-9_-]+)\.js', line)
        if match:
            return match.group(1)

    return None


def parse_function_name(lines: List[str], start_idx: int, look_back: int = 50) -> Optional[str]:
    """
    Try to find a function name by looking backwards from the current position.
    Searches for patterns like:
    - "Function: <name>"
    - "Compiling: <name>"
    - JavaScript function patterns
    Returns function name if found, None otherwise.
    """
    # Look backwards from start_idx
    for i in range(max(0, start_idx - look_back), start_idx):
        line = lines[i]

        # Pattern: Function: name or Compiling: name
        match = re.search(r'(?:Function|Compiling):\s*(\S+)', line)
        if match:
            return match.group(1)

        # Pattern: JavaScript function name(...)
        match = re.search(r'function\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(', line)
        if match:
            return match.group(1)

    return None


def parse_log_section(lines: List[str], start_idx: int) -> AnalysisResult:
    """
    Parse a single compilation unit section (from opportunities through both IR dumps).
    """
    opportunities = []
    spill_mappings = {}
    loads_before = []
    loads_after = []
    fixed_loads = {}
    ir_before = IRSection(is_after_fix=False)
    ir_after = IRSection(is_after_fix=True)

    # Try to extract test name and function name from context
    test_name = parse_test_name(lines, start_idx)
    function_name = parse_function_name(lines, start_idx)

    idx = start_idx
    state = 'opportunities'
    current_opp = None
    current_bb = -1
    current_bb_freq = 1.0
    current_ir_block = None

    while idx < len(lines):
        line = lines[idx]

        # Check for section boundaries
        if '=== SPILL SLOT MAPPING FOR OPPORTUNITIES ===' in line:
            state = 'mappings'
            idx += 1
            continue
        elif '=== AIR BEFORE REGISTER ASSIGNMENT' in line:
            state = 'ir_before'
            current_bb = -1
            current_ir_block = None
            idx += 1
            continue
        elif '=== END IR ===' in line:
            # End of IR BEFORE section - transition to IR AFTER
            if state == 'ir_before':
                # Save the last block if any
                if current_ir_block:
                    ir_before.blocks[current_ir_block.bb_num] = current_ir_block
                state = 'ir_after'
                current_bb = -1
                current_ir_block = None
            idx += 1
            continue
        elif '=== AIR AFTER fixObviousSpills ===' in line:
            # Marker for start of IR AFTER content (already in ir_after state)
            # Just skip this line and continue parsing
            idx += 1
            continue
        elif '=== END IR (after fixObviousSpills) ===' in line:
            # End of IR AFTER section
            if current_ir_block:
                ir_after.blocks[current_ir_block.bb_num] = current_ir_block
            # End of this section
            break
        elif line.strip() == '' or line.startswith('   num'):
            # Skip empty lines and statistics lines
            idx += 1
            continue

        # Parse based on current state
        if state == 'opportunities':
            if '=== INTRA-BLOCK SPLIT OPPORTUNITY ===' in line:
                if current_opp:
                    opportunities.append(current_opp)
                current_opp = None
                idx += 1
                continue

            if not current_opp:
                # Try to parse opportunity header
                header = parse_opportunity_header(line)
                if header:
                    tmp_name, num_clusters, benefit = header
                    current_opp = SplitOpportunity(
                        tmp_name=tmp_name,
                        num_clusters=num_clusters,
                        total_benefit=benefit,
                        test_name=test_name,
                        function_name=function_name
                    )
            else:
                # Try to parse cluster line
                cluster = parse_cluster_line(line)
                if cluster:
                    current_opp.clusters.append(cluster)
                    current_opp.basic_blocks.add(cluster.bb_num)

        elif state == 'mappings':
            mapping = parse_spill_mapping(line)
            if mapping:
                tmp_name, spill_slot = mapping
                spill_mappings[tmp_name] = spill_slot

        elif state in ['ir_before', 'ir_after']:
            parsed = parse_air_instruction(line)
            if parsed:
                bb_num, instruction, spill_slot, frequency = parsed
                if bb_num >= 0:
                    # New basic block starts
                    # Save the previous block if any
                    if current_ir_block:
                        current_ir_block.line_end = idx - 1
                        if state == 'ir_before':
                            ir_before.blocks[current_ir_block.bb_num] = current_ir_block
                        else:
                            ir_after.blocks[current_ir_block.bb_num] = current_ir_block

                    # Start new block
                    current_bb = bb_num
                    current_bb_freq = frequency
                    current_ir_block = IRBasicBlock(bb_num=bb_num, frequency=frequency, line_start=idx)
                    current_ir_block.instructions.append(line.rstrip())
                elif current_ir_block and line.strip().startswith('Air'):
                    # Regular instruction within a block
                    current_ir_block.instructions.append(line.rstrip())

                    # Check for spill slot load
                    if spill_slot and current_bb >= 0:
                        load = SpillSlotLoad(
                            bb_num=current_bb,
                            inst_line=instruction,
                            spill_slot=spill_slot,
                            dest_reg='',
                            line_num=idx
                        )
                        if state == 'ir_before':
                            loads_before.append(load)
                        else:
                            loads_after.append(load)
            elif current_ir_block and line.strip().startswith('Air'):
                # Other Air instruction
                current_ir_block.instructions.append(line.rstrip())

        idx += 1

    # Add the last opportunity if any
    if current_opp:
        opportunities.append(current_opp)

    # Match spill slots to opportunities
    for opp in opportunities:
        if opp.tmp_name in spill_mappings:
            opp.spill_slot = spill_mappings[opp.tmp_name]

    # Analyze which loads were fixed
    # Build a set of (bb, spill_slot) pairs from before
    loads_before_set = {(load.bb_num, load.spill_slot) for load in loads_before}
    loads_after_set = {(load.bb_num, load.spill_slot) for load in loads_after}

    # A load is "fixed" if it appears in before but not in after
    for key in loads_before_set:
        fixed_loads[key] = key not in loads_after_set

    return AnalysisResult(
        opportunities=opportunities,
        spill_mappings=spill_mappings,
        loads_before=loads_before,
        loads_after=loads_after,
        fixed_loads=fixed_loads,
        ir_before=ir_before,
        ir_after=ir_after,
        test_name=test_name,
        compilation_unit=function_name  # Use function_name as compilation unit identifier
    )


def parse_log_file(filepath: str) -> List[AnalysisResult]:
    """
    Parse the entire log file, which may contain multiple compilation units.
    """
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"ERROR: Log file not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    except PermissionError:
        print(f"ERROR: Permission denied reading log file: {filepath}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Failed to read log file: {e}", file=sys.stderr)
        sys.exit(1)

    results = []
    idx = 0

    print(f"Parsing log file ({len(lines)} lines)...")

    if len(lines) == 0:
        print("WARNING: Log file is empty.", file=sys.stderr)
        return results

    # Find all compilation unit starts
    opportunities_found = 0
    while idx < len(lines):
        if '=== INTRA-BLOCK SPLIT OPPORTUNITY ===' in lines[idx]:
            opportunities_found += 1
            # Found the start of a new section
            try:
                result = parse_log_section(lines, idx)
                if result.opportunities:
                    results.append(result)
            except Exception as e:
                print(f"WARNING: Error parsing section starting at line {idx}: {e}", file=sys.stderr)
            # Skip forward to avoid re-parsing
            idx += 1000  # Heuristic: skip ahead to speed up parsing
        else:
            idx += 1

    if opportunities_found == 0:
        print("WARNING: No split opportunity markers found in log file.", file=sys.stderr)
        print("Expected to find lines containing '=== INTRA-BLOCK SPLIT OPPORTUNITY ==='", file=sys.stderr)

    return results


def annotate_ir_instruction(instruction: str, spill_slot: str, is_opportunity_block: bool,
                            cluster_info: str, before_instructions: Set[str],
                            after_instructions: Set[str], is_after: bool) -> str:
    """
    Annotate a single IR instruction with relevant information.
    """
    annotation_parts = []

    # Check if this is a load from the spill slot
    load_match = re.search(rf'\bMove(?:\d+|<[^>]+>)?\s+\({spill_slot}\)', instruction)
    # Check if this is a store to the spill slot
    store_match = re.search(rf'\bMove(?:\d+|<[^>]+>)?\s+[^,]+,\s*\({spill_slot}\)', instruction)

    if load_match:
        if is_after and instruction in before_instructions:
            annotation_parts.append("LOAD from spill slot - NOT OPTIMIZED (still loading from stack)")
        else:
            annotation_parts.append("LOAD from spill slot")
    elif store_match:
        if is_after and instruction in before_instructions:
            annotation_parts.append("STORE to spill slot - NOT OPTIMIZED (still storing to stack)")
        else:
            annotation_parts.append("STORE to spill slot")
    elif spill_slot in instruction:
        # Other uses of the spill slot
        annotation_parts.append(f"uses {spill_slot}")

    if annotation_parts:
        return f"{instruction}   <- {', '.join(annotation_parts)}"
    return instruction


def extract_ir_for_opportunity(opp: SplitOpportunity, result: AnalysisResult,
                               max_lines_per_block: int = 50) -> Dict[str, any]:
    """
    Extract and annotate IR for a specific opportunity.
    Returns a dict with 'blocks_info', 'ir_before_annotated', 'ir_after_annotated'.
    """
    if not opp.spill_slot or not result.ir_before or not result.ir_after:
        return None

    spill_slot = opp.spill_slot
    affected_blocks = sorted(opp.basic_blocks)

    # Build cluster info for each block
    cluster_by_block = {}
    for cluster in opp.clusters:
        cluster_by_block[cluster.bb_num] = cluster

    # Extract IR for affected blocks
    blocks_info = []
    ir_before_annotated = []
    ir_after_annotated = []

    for bb_num in affected_blocks[:10]:  # Limit to first 10 blocks
        if bb_num not in result.ir_before.blocks:
            continue

        block_before = result.ir_before.blocks[bb_num]
        block_after = result.ir_after.blocks.get(bb_num)

        cluster = cluster_by_block.get(bb_num)
        cluster_info = ""
        if cluster:
            cluster_info = f"freq={cluster.frequency:.0f}, {cluster.num_uses} uses"

        blocks_info.append({
            'bb_num': bb_num,
            'frequency': block_before.frequency,
            'cluster': cluster_info,
            'num_instructions': len(block_before.instructions)
        })

        # Build sets of instructions for comparison
        before_insts = set(block_before.instructions[1:])  # Skip BB header
        after_insts = set(block_after.instructions[1:]) if block_after else set()

        # Annotate BEFORE
        ir_before_annotated.append("")
        header = f"BB#{bb_num}:"
        if cluster:
            header += f"  <- OPPORTUNITY CLUSTER ({cluster_info})"
        ir_before_annotated.append(header)

        for inst in block_before.instructions[1:max_lines_per_block]:
            annotated = annotate_ir_instruction(
                inst, spill_slot, True, cluster_info,
                before_insts, after_insts, False
            )
            ir_before_annotated.append("  " + annotated)

        if len(block_before.instructions) > max_lines_per_block:
            ir_before_annotated.append(f"  ... ({len(block_before.instructions) - max_lines_per_block} more instructions)")

        # Annotate AFTER
        if block_after:
            ir_after_annotated.append("")
            ir_after_annotated.append(f"BB#{bb_num}:")

            for inst in block_after.instructions[1:max_lines_per_block]:
                annotated = annotate_ir_instruction(
                    inst, spill_slot, True, cluster_info,
                    before_insts, after_insts, True
                )
                ir_after_annotated.append("  " + annotated)

            if len(block_after.instructions) > max_lines_per_block:
                ir_after_annotated.append(f"  ... ({len(block_after.instructions) - max_lines_per_block} more instructions)")

    return {
        'blocks_info': blocks_info,
        'ir_before_annotated': ir_before_annotated,
        'ir_after_annotated': ir_after_annotated,
        'affected_blocks': affected_blocks
    }


def get_top_unfixed_opportunities(analysis: Dict, top_n: int = 5) -> List[Tuple[SplitOpportunity, AnalysisResult, float, int, int]]:
    """
    Get the top N opportunities that are NOT fully fixed, prioritized by benefit × unfixed percentage.
    Returns list of (opportunity, parent_result, unfixed_score, blocks_fixed, total_blocks).
    """
    unfixed_opportunities = []

    for result in analysis['results']:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            total_blocks = len(opp.basic_blocks)
            unfixed_blocks = total_blocks - blocks_fixed

            if unfixed_blocks > 0:  # Has unfixed blocks
                unfixed_percentage = unfixed_blocks / total_blocks
                # Score = benefit × unfixed percentage (prioritize high benefit with low fix rate)
                unfixed_score = opp.total_benefit * unfixed_percentage
                unfixed_opportunities.append((opp, result, unfixed_score, blocks_fixed, total_blocks))

    # Sort by unfixed_score descending
    unfixed_opportunities.sort(key=lambda x: x[2], reverse=True)

    return unfixed_opportunities[:top_n]


def generate_detailed_ir_analysis(analysis: Dict, top_n: int = 5) -> str:
    """
    Generate detailed IR analysis for the top N unfixed opportunities.
    """
    lines = []

    lines.append("")
    lines.append("=" * 80)
    lines.append(f"DETAILED IR ANALYSIS OF TOP {top_n} UNFIXED OPPORTUNITIES")
    lines.append("=" * 80)
    lines.append("")
    lines.append("This section shows the actual AIR (Assembly IR) code for opportunities that")
    lines.append("were NOT fully optimized by fixObviousSpills, making them prime candidates for")
    lines.append("intra-block splitting. Each opportunity shows:")
    lines.append("  - IR BEFORE: Code before fixObviousSpills optimization")
    lines.append("  - IR AFTER: Code after fixObviousSpills optimization")
    lines.append("  - Annotations highlight spill slot loads/stores and whether they were optimized")
    lines.append("")

    top_unfixed = get_top_unfixed_opportunities(analysis, top_n)

    if not top_unfixed:
        lines.append("No unfixed opportunities found.")
        return "\n".join(lines)

    for rank, (opp, result, unfixed_score, blocks_fixed, total_blocks) in enumerate(top_unfixed, 1):
        lines.append("")
        lines.append("=" * 80)
        lines.append(f"#{rank}: {opp.tmp_name}")
        if opp.test_name or opp.function_name:
            if opp.test_name:
                lines.append(f"Test: {opp.test_name}")
            if opp.function_name:
                lines.append(f"Function: {opp.function_name}")
        lines.append("=" * 80)

        fix_rate = blocks_fixed / total_blocks if total_blocks > 0 else 0
        unfixed_rate = 1.0 - fix_rate

        lines.append(f"Benefit: {opp.total_benefit:.2f}")
        lines.append(f"Spill slot: {opp.spill_slot}")
        lines.append(f"Blocks fixed: {blocks_fixed}/{total_blocks} ({fix_rate*100:.1f}%)")
        lines.append(f"Unfixed score: {unfixed_score:.2f} (benefit × {unfixed_rate*100:.1f}% unfixed)")
        lines.append("")

        # Extract and annotate IR
        ir_data = extract_ir_for_opportunity(opp, result, max_lines_per_block=30)

        if not ir_data:
            lines.append("IR data not available for this opportunity.")
            continue

        # Show affected blocks summary
        lines.append(f"Affected basic blocks: {', '.join(f'BB#{bb}' for bb in ir_data['affected_blocks'][:15])}")
        if len(ir_data['affected_blocks']) > 15:
            lines.append(f"  ... and {len(ir_data['affected_blocks']) - 15} more")
        lines.append("")

        # Show clusters info
        lines.append("Use clusters:")
        for block_info in ir_data['blocks_info']:
            lines.append(f"  BB#{block_info['bb_num']}: {block_info['cluster']}")
        lines.append("")

        # Show IR BEFORE
        lines.append("-" * 80)
        lines.append("IR BEFORE fixObviousSpills:")
        lines.append("-" * 80)
        lines.extend(ir_data['ir_before_annotated'])
        lines.append("")

        # Show IR AFTER
        lines.append("-" * 80)
        lines.append("IR AFTER fixObviousSpills:")
        lines.append("-" * 80)
        lines.extend(ir_data['ir_after_annotated'])
        lines.append("")

        # Analysis summary
        lines.append("-" * 80)
        lines.append("ANALYSIS:")
        lines.append("-" * 80)
        if fix_rate < 0.5:
            lines.append(f"** HIGH PRIORITY: Less than half the blocks were optimized ({fix_rate*100:.1f}%)")
            lines.append("   Intra-block splitting could provide significant benefit here.")
        elif fix_rate < 1.0:
            lines.append(f"** MODERATE PRIORITY: Some blocks remain unfixed ({unfixed_rate*100:.1f}%)")
            lines.append("   Intra-block splitting could help with the remaining blocks.")

        # Check if loads are still present in the after IR
        loads_still_present = False
        for line in ir_data['ir_after_annotated']:
            if 'NOT OPTIMIZED' in line:
                loads_still_present = True
                break

        if loads_still_present:
            lines.append("   Spill slot loads/stores are still present in the optimized IR,")
            lines.append("   indicating fixObviousSpills could not eliminate them.")

        lines.append("")

    return "\n".join(lines)


def analyze_results(results: List[AnalysisResult]) -> Dict:
    """
    Aggregate and analyze results from all compilation units.
    """
    # Collect all opportunities
    all_opportunities = []
    for result in results:
        all_opportunities.extend(result.opportunities)

    # Sort by benefit descending
    all_opportunities.sort(key=lambda x: x.total_benefit, reverse=True)

    # Analyze top 10
    top_10_analysis = []
    for opp in all_opportunities[:10]:
        # Find which result this opportunity belongs to
        parent_result = None
        for result in results:
            if opp in result.opportunities:
                parent_result = result
                break

        if not parent_result:
            continue

        # Count how many blocks had loads that were fixed
        blocks_fixed = 0
        if opp.spill_slot:
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in parent_result.fixed_loads and parent_result.fixed_loads[key]:
                    blocks_fixed += 1

        top_10_analysis.append({
            'opportunity': opp,
            'blocks_fixed': blocks_fixed,
            'total_blocks': len(opp.basic_blocks),
            'fix_rate': blocks_fixed / len(opp.basic_blocks) if opp.basic_blocks else 0
        })

    # Overall statistics
    total_opportunities = len(all_opportunities)
    opportunities_with_some_fixes = 0
    opportunities_fully_fixed = 0

    for result in results:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            if blocks_fixed > 0:
                opportunities_with_some_fixes += 1
            if blocks_fixed == len(opp.basic_blocks):
                opportunities_fully_fixed += 1

    return {
        'all_opportunities': all_opportunities,
        'top_10_analysis': top_10_analysis,
        'total_opportunities': total_opportunities,
        'opportunities_with_some_fixes': opportunities_with_some_fixes,
        'opportunities_fully_fixed': opportunities_fully_fixed,
        'results': results
    }


def generate_report(analysis: Dict) -> str:
    """
    Generate a human-readable report from the analysis.
    """
    report_lines = []

    report_lines.append("=" * 80)
    report_lines.append("JSC INTRA-BLOCK SPLIT OPPORTUNITY ANALYSIS REPORT")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append("This report analyzes intra-block split opportunities identified by JSC's")
    report_lines.append("register allocator and determines which ones were optimized away by the")
    report_lines.append("fixObviousSpills pass.")
    report_lines.append("")
    report_lines.append("KEY INSIGHT:")
    report_lines.append("- If fixObviousSpills optimized all blocks for an opportunity, splitting")
    report_lines.append("  is NOT needed (the redundant spills were already removed).")
    report_lines.append("- If blocks remain unfixed, intra-block splitting could provide benefit")
    report_lines.append("  by keeping the value in a register within those hot blocks.")
    report_lines.append("")

    # Check if we have test/function name information
    has_test_names = any(opp.test_name for result in analysis['results'] for opp in result.opportunities)
    has_function_names = any(opp.function_name for result in analysis['results'] for opp in result.opportunities)

    if not has_test_names and not has_function_names:
        report_lines.append("NOTE: Test names and function names were not found in the log file.")
        report_lines.append("To add this information, you would need to:")
        report_lines.append("  1. Modify the JetStream3 test runner to output test names before each test")
        report_lines.append("  2. Modify JSC's AIR dump to include function names in compilation unit headers")
        report_lines.append("")

    # Overall statistics
    report_lines.append("OVERALL STATISTICS")
    report_lines.append("-" * 80)
    report_lines.append(f"Total split opportunities found: {analysis['total_opportunities']}")
    report_lines.append(f"Opportunities with some blocks fixed: {analysis['opportunities_with_some_fixes']} "
                       f"({100.0 * analysis['opportunities_with_some_fixes'] / max(1, analysis['total_opportunities']):.1f}%)")
    report_lines.append(f"Opportunities fully fixed: {analysis['opportunities_fully_fixed']} "
                       f"({100.0 * analysis['opportunities_fully_fixed'] / max(1, analysis['total_opportunities']):.1f}%)")
    not_fixed = analysis['total_opportunities'] - analysis['opportunities_with_some_fixes']
    report_lines.append(f"Opportunities NOT fixed at all: {not_fixed} "
                       f"({100.0 * not_fixed / max(1, analysis['total_opportunities']):.1f}%)")
    report_lines.append("")

    # Top 10 opportunities
    report_lines.append("TOP 10 SPLIT OPPORTUNITIES (by benefit)")
    report_lines.append("-" * 80)
    report_lines.append(f"{'Rank':<6}{'Tmp':<12}{'Benefit':<12}{'Clusters':<10}{'Blocks':<8}{'Fixed':<8}{'Fix %':<8}{'Spill Slot':<12}")
    report_lines.append("-" * 80)

    for rank, item in enumerate(analysis['top_10_analysis'], 1):
        opp = item['opportunity']
        report_lines.append(
            f"{rank:<6}"
            f"{opp.tmp_name:<12}"
            f"{opp.total_benefit:<12.2f}"
            f"{opp.num_clusters:<10}"
            f"{item['total_blocks']:<8}"
            f"{item['blocks_fixed']:<8}"
            f"{item['fix_rate']*100:<7.1f}%"
            f"{opp.spill_slot or 'N/A':<12}"
        )
        # Add test/function name info if available
        if opp.test_name or opp.function_name:
            info_parts = []
            if opp.test_name:
                info_parts.append(f"Test: {opp.test_name}")
            if opp.function_name:
                info_parts.append(f"Function: {opp.function_name}")
            report_lines.append(f"        [{', '.join(info_parts)}]")

    report_lines.append("")

    # Detailed analysis of top 10
    report_lines.append("DETAILED ANALYSIS OF TOP 10 OPPORTUNITIES")
    report_lines.append("-" * 80)

    for rank, item in enumerate(analysis['top_10_analysis'], 1):
        opp = item['opportunity']
        report_lines.append("")
        report_lines.append(f"#{rank}: {opp.tmp_name} (benefit: {opp.total_benefit:.2f})")
        if opp.test_name:
            report_lines.append(f"  Test: {opp.test_name}")
        if opp.function_name:
            report_lines.append(f"  Function: {opp.function_name}")
        report_lines.append(f"  Spill slot: {opp.spill_slot or 'N/A'}")
        report_lines.append(f"  Number of clusters: {opp.num_clusters}")
        report_lines.append(f"  Basic blocks involved: {sorted(opp.basic_blocks)[:10]}"
                           f"{' ...' if len(opp.basic_blocks) > 10 else ''}")
        report_lines.append(f"  Blocks with loads fixed: {item['blocks_fixed']}/{item['total_blocks']} "
                           f"({item['fix_rate']*100:.1f}%)")

        if item['fix_rate'] < 1.0:
            report_lines.append(f"  ** NEEDS SPLITTING: Not all blocks were optimized by fixObviousSpills **")

    report_lines.append("")

    # Opportunities that need splitting (not fully fixed)
    needs_splitting = []
    for result in analysis['results']:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            if blocks_fixed < len(opp.basic_blocks):
                needs_splitting.append((opp, blocks_fixed, len(opp.basic_blocks)))

    # Sort by benefit
    needs_splitting.sort(key=lambda x: x[0].total_benefit, reverse=True)

    report_lines.append("OPPORTUNITIES THAT NEED SPLITTING (not fully optimized)")
    report_lines.append("-" * 80)
    report_lines.append(f"Total: {len(needs_splitting)} opportunities")
    report_lines.append("")
    report_lines.append(f"{'Tmp':<12}{'Benefit':<12}{'Clusters':<10}{'Fixed':<15}{'Spill Slot':<12}")
    report_lines.append("-" * 80)

    for opp, fixed, total in needs_splitting[:50]:  # Show top 50
        report_lines.append(
            f"{opp.tmp_name:<12}"
            f"{opp.total_benefit:<12.2f}"
            f"{opp.num_clusters:<10}"
            f"{fixed}/{total:<13}"
            f"{opp.spill_slot or 'N/A':<12}"
        )

    if len(needs_splitting) > 50:
        report_lines.append(f"... and {len(needs_splitting) - 50} more")

    report_lines.append("")

    # Add prioritized recommendations
    report_lines.append("PRIORITIZED RECOMMENDATIONS FOR INTRA-BLOCK SPLITTING")
    report_lines.append("-" * 80)
    report_lines.append("These opportunities have high benefit and were NOT fully optimized by")
    report_lines.append("fixObviousSpills, making them prime candidates for intra-block splitting:")
    report_lines.append("")

    high_benefit_unfixed = []
    for result in analysis['results']:
        for opp in result.opportunities:
            if not opp.spill_slot or not opp.basic_blocks:
                continue

            blocks_fixed = 0
            for bb in opp.basic_blocks:
                key = (bb, opp.spill_slot)
                if key in result.fixed_loads and result.fixed_loads[key]:
                    blocks_fixed += 1

            if blocks_fixed < len(opp.basic_blocks) and opp.total_benefit > 1000:
                fix_rate = blocks_fixed / len(opp.basic_blocks)
                high_benefit_unfixed.append((opp, blocks_fixed, len(opp.basic_blocks), fix_rate))

    # Sort by benefit
    high_benefit_unfixed.sort(key=lambda x: x[0].total_benefit, reverse=True)

    report_lines.append(f"{'Tmp':<12}{'Benefit':<15}{'Clusters':<10}{'Fixed':<12}{'Fix %':<10}{'Priority':<10}")
    report_lines.append("-" * 80)

    for opp, fixed, total, fix_rate in high_benefit_unfixed[:20]:
        if opp.total_benefit > 1000000:
            priority = "CRITICAL"
        elif opp.total_benefit > 100000:
            priority = "HIGH"
        elif opp.total_benefit > 10000:
            priority = "MEDIUM"
        else:
            priority = "LOW"

        report_lines.append(
            f"{opp.tmp_name:<12}"
            f"{opp.total_benefit:<15.2f}"
            f"{opp.num_clusters:<10}"
            f"{fixed}/{total:<10}"
            f"{fix_rate*100:>8.1f}% "
            f"{priority:<10}"
        )

    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append("END OF REPORT")
    report_lines.append("=" * 80)

    # Add detailed IR analysis
    detailed_ir = generate_detailed_ir_analysis(analysis, top_n=5)
    report_lines.append("")
    report_lines.append(detailed_ir)

    return "\n".join(report_lines)


def export_to_csv(analysis: Dict, csv_file: str):
    """
    Export the analysis results to a CSV file for further analysis.
    """
    try:
        with open(csv_file, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'Tmp', 'Benefit', 'Num_Clusters', 'Total_Blocks', 'Blocks_Fixed',
                'Fix_Rate', 'Spill_Slot', 'Basic_Blocks', 'Priority', 'Test_Name', 'Function_Name'
            ])

            # Collect all opportunities with their fix status
            for result in analysis['results']:
                for opp in result.opportunities:
                    if not opp.spill_slot or not opp.basic_blocks:
                        continue

                    blocks_fixed = 0
                    for bb in opp.basic_blocks:
                        key = (bb, opp.spill_slot)
                        if key in result.fixed_loads and result.fixed_loads[key]:
                            blocks_fixed += 1

                    fix_rate = blocks_fixed / len(opp.basic_blocks) if opp.basic_blocks else 0

                    # Determine priority
                    if opp.total_benefit > 1000000:
                        priority = "CRITICAL"
                    elif opp.total_benefit > 100000:
                        priority = "HIGH"
                    elif opp.total_benefit > 10000:
                        priority = "MEDIUM"
                    else:
                        priority = "LOW"

                    writer.writerow([
                        opp.tmp_name,
                        f"{opp.total_benefit:.2f}",
                        opp.num_clusters,
                        len(opp.basic_blocks),
                        blocks_fixed,
                        f"{fix_rate:.2f}",
                        opp.spill_slot,
                        ','.join(str(bb) for bb in sorted(opp.basic_blocks)[:20]),
                        priority if blocks_fixed < len(opp.basic_blocks) else "N/A",
                        opp.test_name or '',
                        opp.function_name or ''
                    ])

        print(f"CSV export saved to: {csv_file}")
    except Exception as e:
        print(f"Warning: Could not save CSV export: {e}", file=sys.stderr)


def main():
    if len(sys.argv) != 2 or sys.argv[1] in ['-h', '--help', 'help']:
        print(__doc__)
        if len(sys.argv) == 2 and sys.argv[1] in ['-h', '--help', 'help']:
            sys.exit(0)
        else:
            print("\nERROR: Log file path required.", file=sys.stderr)
            sys.exit(1)

    log_file = sys.argv[1]

    print(f"Analyzing JSC split opportunity log: {log_file}")
    print("")

    # Parse the log file
    results = parse_log_file(log_file)

    if not results:
        print("WARNING: No split opportunities found in the log file.", file=sys.stderr)
        print("The log file may be incomplete or in an unexpected format.", file=sys.stderr)
        sys.exit(0)

    print(f"Found {len(results)} compilation units with split opportunities.")
    print("")

    # Analyze the results
    analysis = analyze_results(results)

    # Generate and print the report
    report = generate_report(analysis)
    print(report)

    # Save report to file
    output_file = log_file.rsplit('.', 1)[0] + '_analysis_report.txt'
    try:
        with open(output_file, 'w') as f:
            f.write(report)
        print("")
        print(f"Report saved to: {output_file}")
    except Exception as e:
        print(f"Warning: Could not save report to file: {e}", file=sys.stderr)

    # Export to CSV
    csv_file = log_file.rsplit('.', 1)[0] + '_analysis.csv'
    export_to_csv(analysis, csv_file)


if __name__ == '__main__':
    main()
